# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/58768543-bb82-4748-a1c0-4b734b864125";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6d3ce885-b69a-452c-9b0e-b04732f9c653".device = "/dev/disk/by-uuid/6d3ce885-b69a-452c-9b0e-b04732f9c653";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8266-108B";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # Mount Windows drive
  fileSystems."/home/jasonk/SecondDrive" = {
    device = "/dev/disk/by-uuid/BA2AB5EF2AB5A931";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000" # Your user ID (jasonk)
      "gid=100" # users group
      "dmask=022"
      "fmask=133"
      "big_writes"
      "nofail" # Don't fail boot if drive is missing
      "x-systemd.automount" # Automount on access
      "x-systemd.device-timeout=5" # Timeout for device availability
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
